services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always

  ecommerce-app:
    image: mingi3487/study_project:latest
    container_name: ecommerce-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: redis
    depends_on:
      - redis
    restart: always