#spring:
#  profiles:
#    include: jwt,redis

spring:
  profiles:
    group:
      default:
        - jwt
        - redis
        - aws
        - payment
      test:
        - test

  data:
    web:
      pageable:
        one-indexed-parameters: true

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#    database-platform: org.hibernate.dialect.H2Dialect


  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # multipartFile 용량 늘려주는 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


#  session:
#    timeout: 86400
#
#server:
#  servlet:
#    session:
#      cookie:
#        max-age: 172800


logging:
  level:
    org.hibernate.sql: debug














