name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub 리포지토리 Checkout
        uses: actions/checkout@v3

      - name: SSH Key 설정
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: EC2 호스트 등록
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: EC2에 ~/app 디렉토리 만들기
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} "mkdir -p ~/app"

      - name: docker-compose.yml 파일 EC2로 복사
        working-directory: ${{ github.workspace }}
        run: |
          scp -i ~/.ssh/id_rsa docker-compose.yml ec2-user@${{ secrets.EC2_HOST }}:~/app/docker-compose.yml

      - name: EC2에 접속해서 배포 실행
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} << EOF
            echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" > ~/app/.env
            cd ~/app
          
            sudo mkdir -p /usr/local/lib/docker/cli-plugins
            sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
              -o /usr/local/lib/docker/cli-plugins/docker-compose
            sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
  
            doker compose version

            docker pull ${{ secrets.DOCKER_USERNAME }}/study_project:latest
            docker compose down --volumes --remove-orphans || true
            docker compose up -d
          EOF