name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Key 설정
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: EC2 호스트 등록
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: docker-compose.yml 파일 EC2로 복사
        run: |
          scp -i ~/.ssh/id_rsa ./docker-compose.yml ec2-user@${{ secrets.EC2_HOST }}:~/home/app/docker-compose.yml

      - name: EC2에 접속해서 배포 실행
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} << EOF
          
            echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" > ~/home/app/.env
          
            cd ~/home/app  
          
            docker pull ${{ secrets.DOCKER_USERNAME }}/study_project:latest
          
            docker-compose down || true
            docker-compose up -d
          
          EOF