name: CI - Build and Push Docker Image

on:
  push:
    branches: [ master ]  # master 브랜치에 push 될 때만 동작

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 받아오기
        uses: actions/checkout@v2

      - name: Give gradlew permission
        run: chmod +x ./gradlew

      - name: JDK 17 설치
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 빌드 실행
        run: ./gradlew build

      - name: DockerHub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이미지 빌드
        run: docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/study_project:latest .

      - name: DockerHub에 업로드
        run: docker push ${{ secrets.DOCKER_USERNAME }}/study_project:latest